### ISSUE TITLE
django cms 4.1.1: get_placeholders() missing 1 required positional argument: 'language'

### ISSUE THREAD

**Issue by i-salameh95** [django-cms/django-cms#8134]
This code was already working correctly in django cms 3.11 
```
#cms_menus.py
import lxml.html
from cms.menu_bases import CMSAttachMenu
from cms.plugin_rendering import ContentRenderer
from cms.utils.placeholder import get_placeholders
from django.template.context import RequestContext
from django.template.loader import get_template
from django.utils.translation import gettext_lazy as _
from lxml import etree
from menus.base import NavigationNode
from menus.menu_pool import menu_pool


class AnchorsMenu(CMSAttachMenu):
    name = _("anchors menu")

    def get_nodes(self, request):
        nodes = []

        if not self.instance:
            return []

        # toolbar = get_toolbar_from_request(request)
        content = ''
        context = RequestContext(request)
        template = self.instance.get_template()
        slots = [p.slot for p in get_placeholders(template)]
        with context.bind_template(get_template(template).template):
            for ph in self.instance.get_placeholders().filter(slot__in=slots):
                renderer = ContentRenderer(request=request)
                content += renderer.render_placeholder(
                    placeholder=ph,
                    context=context
                )
        if not content:
            return nodes
        try:
            html = lxml.html.fromstring(content)
        except etree.ParserError:
            return nodes
        anchors = html.xpath('//a[@name]')
        base_url = self.instance.get_absolute_url()
        for h in anchors:
            name = h.get('name')
            nodes.append(NavigationNode(h.text, '%s#%s' % (base_url, name), name))
        return nodes


menu_pool.register_menu(AnchorsMenu)

```

now after upgrading to django cms 4.1.1  it shows the following error:
get_placeholders() missing 1 required positional argument: 'language'  

and after I update the code and add 
language = get_current_language() , it shows another error:

get placeholder should return 1, but it returns 2 instead.

**Comment by i-salameh95** [comment]
the second error comes after I have made the update on the code 
```
language = get_current_language()
for ph in self.instance.get_placeholders(language).filter(slot__in=slots):
```

then when I refresh it shows: get_placeholders() should return 1, but it returns 2 instead!

**Comment by i-salameh95** [comment]
I'm feeling hopeless, and the whole upgrading process on my project is risky, 
I will wait until I have found fixes for my special code, especially the extensions one which reported here:
https://github.com/Aiky30/djangocms-4-migration/issues/19 

and then this issue in cms_menus.py

**Comment by piyushchandola2005** [comment]
CAN I WORK ON THIS?

**Comment by piyushchandola2005** [comment]
> the second error comes after I have made the update on the code
> 
> ```
> language = get_current_language()
> for ph in self.instance.get_placeholders(language).filter(slot__in=slots):
> ```
> 
> then when I refresh it shows: get_placeholders() should return 1, but it returns 2 instead!

TRY USING DISTINCT 
placeholders = self.instance.get_placeholders(language).distinct()
