### ISSUE TITLE
Not compatible with django-reversion 1.5+?

### ISSUE THREAD

**Issue by victorhooi** [django-cms/django-cms#1101]
Hi,

I know the django-cms docs recommend to use with django-reversion 1.4, but I thought I'd try against the both django-reversion 1.5 and the latest trunk-reversion just to see what happened.

It gives an error about a missing RegistrationInfo:

```
from reversion.revisions import RegistrationError, RegistrationInfo
ImportError: cannot import name RegistrationInfo
```

The RegistrationInfo method seems to have been removed around 31 August, 2011 in git commit 483613dddb.

You can see it still exists here:

https://github.com/etianen/django-reversion/blob/293cfd7faae0cf9ee2a7b2cf0728e15777458d24/src/reversion/revisions.py

But has been removed in the next commit:

https://github.com/etianen/django-reversion/blob/483613dddb2109d72db215eba7d64d297388493d/src/reversion/revisions.py

Is there any chance django-cms can be fixed to work with django-reveresion 1.5+? There are some nice improvements since then, as well as bug fixes, and it'd be nice to be able take advantage of those.

Cheers,
Victor
